services:
  db:
    image: postgres:17
    container_name: db_app
    environment:
      - POSTGRES_USER=usuario
      - POSTGRES_PASSWORD=usuario
      - POSTGRES_DB=curriculos_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/postgres_data
    networks:
      - app-network
      

    networks:
      - app-network
      

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
