services:
  db:
    image: postgres:15
    container_name: db_app
    environment:
      - POSTGRES_USER=usuario
      - POSTGRES_PASSWORD=usuario
      - POSTGRES_DB=curriculos_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/postgres_data

  backend:
    build:
      context: /backend
      dockerfile: Dockerfile
    container_name: springboot
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/curriculos_db
      - SPRING_DATASOURCE_USERNAME:usuario
      - SPRING_DATASOURCE_PASSWORD:usuario
    depends_on:
      - db

volumes:
  postgres_data: