name: CheckStyle

on:
  push:
    
  pull_request:
    
  schedule:
    - cron: '0 3 * * 1'  # Roda toda segunda-feira às 3h UTC

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache local Maven repository
        if: ${{ always() }}
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Instalar Maven
        run: sudo apt-get install -y maven


      - name: ChekStyle
        working-directory: ./backend
        run: |
          mvn clean verify -Pjqassistant
      
      - name: Upload CheckStyle Artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Upload CheckStyle Artifact
          path: |
            /home/runner/work/Cadastro-Curriculo/Cadastro-Curriculo/backend/target/jqassistant/jqassistant-report.xml
