name: OWASP Dependency Check

on:
  push:
  pull_request:
  schedule:
    - cron: '0 3 * * 1'  # Roda toda segunda-feira às 3h UTC

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    env:
      ## NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
      NVD_HOST: ${{ secrets.NVD_HOST }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Cache OWASP Dependency-Check Data
        uses: actions/cache@v4
        with:
          path: ./backend/owasp-data
          key: ${{ runner.os }}-owasp-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-owasp-

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Instalar Maven
        run: sudo apt-get install -y maven

      - name: Gerar Diagramas UML
        working-directory: ./backend
        run: |
          mvn clean verify -Puml-doc

      - name: Upload UML Artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v4.6.2
        with: 
          name: Upload UML Artifacts
          path: |
            /home/runner/work/Cadastro-Curriculo/Cadastro-Curriculo/backend/target/apidocs


      - name: Rodar CheckStyle Plugin
        working-directory: ./backend
        run: |
          mvn clean verify -Pjqassistant

      - name: Upload CheckStyle Artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Upload CheckStyle Artifact
          path: |
            /home/runner/work/Cadastro-Curriculo/Cadastro-Curriculo/backend/target/jqassistant/jqassistant-report.xml

      - name: Rodar PMD codigo duplicado
        working-directory: ./backend
        run: |
          mvn clean verify -Pduplicated-check

      - name: Upload PMD Relatorio
        if: ${{ always() }}
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Upload PMD Relatorio
          path: |
            /home/runner/work/Cadastro-Curriculo/Cadastro-Curriculo/backend/target/cpd.xml

      - name: Rodar PMD code smells
        working-directory: ./backend
        run: |
          mvn clean verify -Pcode-smell-check

      - name: Upload Relatorio Code Smells
        if: ${{ always() }}
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Relatorio code smells
          path: |
            /home/runner/work/Cadastro-Curriculo/Cadastro-Curriculo/backend/target/reports


      # - name: Rodar OWASP Dependency Check
      #   working-directory: ./backend
      #   run: |
      #     mvn clean verify -Pdependency-check \
      #       -Dnvd.api.endpoint=$NVD_HOST \
      #       -Ddata.directory=./owasp-data

      - name: Upload Artifacts OWASP
        if: ${{ always() }}
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Upload OWASP Artifact
          path: |
            /home/runner/work/Cadastro-Curriculo/Cadastro-Curriculo/backend/target/dependency-check-report.html

      - name: SpotBugs
        if: ${{always()}}
        working-directory: ./backend
        run: |
          mvn clean compile -Pspot-bugs-check -DskipTests com.github.spotbugs:spotbugs-maven-plugin:spotbugs

      - name: Upload SpotBugs Artifacts
        if: ${{always()}}
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Upload SpotBugs Artifacts
          path: |
            /home/runner/work/Cadastro-Curriculo/Cadastro-Curriculo/backend/target/site/spotbugs.html


      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        if: ${{always()}}
        working-directory: ./backend
        run: |
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=matheusdev_cadastro-curriculo

##  -Dnvd.api.key=$NVD_API_KEY \
