name: OWASP Dependency Check

on:
  push:
    
  pull_request:
    
  schedule:
    - cron: '0 3 * * 1'  # Roda toda segunda-feira às 3h UTC

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Instalar Maven
        run: sudo apt-get install -y maven

      - name: Rodar OWASP Dependency Check
        working-directory: ./backend
        run: |
          mvn clean verify -Pdependency-check

      - name:  Upload Artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Uplod artifact
          path: |
             /home/runner/work/Cadastro-Curriculo/Cadastro-Curriculo/backend/target/dependency-check-report.html

   
